import {MigrationInterface, QueryRunner} from "typeorm";

export class AddCustomFields1760767894785 implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "IDX_124456e637cca7a415897dce65"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_af13739f4962eab899bdff34be"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_729b3eea7ce540930dbb706949"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_73a78d7df09541ac5eba620d18"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_order" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "type" varchar NOT NULL DEFAULT ('Regular'), "code" varchar NOT NULL, "state" varchar NOT NULL, "active" boolean NOT NULL DEFAULT (1), "orderPlacedAt" datetime, "couponCodes" text NOT NULL, "shippingAddress" text NOT NULL, "billingAddress" text NOT NULL, "currencyCode" varchar NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "aggregateOrderId" integer, "customerId" integer, "taxZoneId" integer, "subTotal" integer NOT NULL, "subTotalWithTax" integer NOT NULL, "shipping" integer NOT NULL DEFAULT (0), "shippingWithTax" integer NOT NULL DEFAULT (0), "customFieldsSchedulevisit" datetime(6), "customFieldsSalespersonname" varchar(255), "customFieldsSalespersoncontact" varchar(255), "customFieldsSalespersonemail" varchar(255), "customFieldsAdvisorselleridid" integer, "customFieldsVisitstatus" varchar(255), "customFieldsScheduledvisitdate" datetime(6), "customFieldsAdvisornotes" varchar(255), "customFieldsLoantype" varchar(255), "customFieldsAdvisorassignedby" varchar(255), "customFieldsAdvisorassignedat" datetime(6), "customFieldsVisitoutcome" varchar(255), "customFieldsVisitmode" varchar(255), "customFieldsVisitlocation" varchar(255), "customFieldsCustomersnapshot" varchar(255), "customFieldsCommunicationconsent" boolean, "customFieldsFollowuprequired" boolean, "customFieldsOrderreference" varchar(255), CONSTRAINT "FK_2efb279cc9029a1fb00b99d961b" FOREIGN KEY ("customFieldsAdvisorselleridid") REFERENCES "seller" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_124456e637cca7a415897dce659" FOREIGN KEY ("customerId") REFERENCES "customer" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_73a78d7df09541ac5eba620d181" FOREIGN KEY ("aggregateOrderId") REFERENCES "order" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_order"("createdAt", "updatedAt", "type", "code", "state", "active", "orderPlacedAt", "couponCodes", "shippingAddress", "billingAddress", "currencyCode", "id", "aggregateOrderId", "customerId", "taxZoneId", "subTotal", "subTotalWithTax", "shipping", "shippingWithTax", "customFieldsSchedulevisit", "customFieldsSalespersonname", "customFieldsSalespersoncontact", "customFieldsSalespersonemail", "customFieldsAdvisorselleridid", "customFieldsVisitstatus", "customFieldsScheduledvisitdate", "customFieldsAdvisornotes", "customFieldsLoantype") SELECT "createdAt", "updatedAt", "type", "code", "state", "active", "orderPlacedAt", "couponCodes", "shippingAddress", "billingAddress", "currencyCode", "id", "aggregateOrderId", "customerId", "taxZoneId", "subTotal", "subTotalWithTax", "shipping", "shippingWithTax", "customFieldsSchedulevisit", "customFieldsSalespersonname", "customFieldsSalespersoncontact", "customFieldsSalespersonemail", "customFieldsAdvisorselleridid", "customFieldsVisitstatus", "customFieldsScheduledvisitdate", "customFieldsAdvisornotes", "customFieldsLoantype" FROM "order"`, undefined);
        await queryRunner.query(`DROP TABLE "order"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_order" RENAME TO "order"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_124456e637cca7a415897dce65" ON "order" ("customerId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_af13739f4962eab899bdff34be" ON "order" ("orderPlacedAt") `, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_729b3eea7ce540930dbb706949" ON "order" ("code") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_73a78d7df09541ac5eba620d18" ON "order" ("aggregateOrderId") `, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_customer" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "title" varchar, "firstName" varchar NOT NULL, "lastName" varchar NOT NULL, "phoneNumber" varchar, "emailAddress" varchar NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "userId" integer, "customFieldsUserrole" varchar(255), "customFieldsAvailableslots" text, "customFieldsScheduledvisits" text, "customFieldsKycstatus" varchar(255), "customFieldsPannumber" varchar(255), "customFieldsOccupation" varchar(255), "customFieldsAlternatenumber" varchar(255), "customFieldsCibilscore" varchar(255), "customFieldsOrderid" varchar(255), "customFieldsAdvisorselleridid" integer, "customFieldsPreferredcontactmethod" varchar(255), CONSTRAINT "REL_3f62b42ed23958b120c235f74d" UNIQUE ("userId"), CONSTRAINT "FK_90f47e7aa8cada41c7f407c0126" FOREIGN KEY ("customFieldsAdvisorselleridid") REFERENCES "seller" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3f62b42ed23958b120c235f74df" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_customer"("createdAt", "updatedAt", "deletedAt", "title", "firstName", "lastName", "phoneNumber", "emailAddress", "id", "userId", "customFieldsUserrole", "customFieldsAvailableslots", "customFieldsScheduledvisits", "customFieldsKycstatus", "customFieldsPannumber", "customFieldsOccupation", "customFieldsAlternatenumber", "customFieldsCibilscore", "customFieldsOrderid", "customFieldsAdvisorselleridid") SELECT "createdAt", "updatedAt", "deletedAt", "title", "firstName", "lastName", "phoneNumber", "emailAddress", "id", "userId", "customFieldsUserrole", "customFieldsAvailableslots", "customFieldsScheduledvisits", "customFieldsKycstatus", "customFieldsPannumber", "customFieldsOccupation", "customFieldsAlternatenumber", "customFieldsCibilscore", "customFieldsOrderid", "customFieldsAdvisorselleridid" FROM "customer"`, undefined);
        await queryRunner.query(`DROP TABLE "customer"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_customer" RENAME TO "customer"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_seller" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "name" varchar NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "customFieldsConnectedaccountid" varchar(255), "customFieldsAdvisortype" varchar(255), "customFieldsServicearea" varchar(255), "customFieldsRating" double precision, "customFieldsWorkinghours" varchar(255), "customFieldsIsactive" boolean DEFAULT (1))`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_seller"("createdAt", "updatedAt", "deletedAt", "name", "id", "customFieldsConnectedaccountid", "customFieldsAdvisortype", "customFieldsServicearea", "customFieldsRating") SELECT "createdAt", "updatedAt", "deletedAt", "name", "id", "customFieldsConnectedaccountid", "customFieldsAdvisortype", "customFieldsServicearea", "customFieldsRating" FROM "seller"`, undefined);
        await queryRunner.query(`DROP TABLE "seller"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_seller" RENAME TO "seller"`, undefined);
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "seller" RENAME TO "temporary_seller"`, undefined);
        await queryRunner.query(`CREATE TABLE "seller" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "name" varchar NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "customFieldsConnectedaccountid" varchar(255), "customFieldsAdvisortype" varchar(255), "customFieldsServicearea" varchar(255), "customFieldsRating" double precision)`, undefined);
        await queryRunner.query(`INSERT INTO "seller"("createdAt", "updatedAt", "deletedAt", "name", "id", "customFieldsConnectedaccountid", "customFieldsAdvisortype", "customFieldsServicearea", "customFieldsRating") SELECT "createdAt", "updatedAt", "deletedAt", "name", "id", "customFieldsConnectedaccountid", "customFieldsAdvisortype", "customFieldsServicearea", "customFieldsRating" FROM "temporary_seller"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_seller"`, undefined);
        await queryRunner.query(`ALTER TABLE "customer" RENAME TO "temporary_customer"`, undefined);
        await queryRunner.query(`CREATE TABLE "customer" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "title" varchar, "firstName" varchar NOT NULL, "lastName" varchar NOT NULL, "phoneNumber" varchar, "emailAddress" varchar NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "userId" integer, "customFieldsUserrole" varchar(255), "customFieldsAvailableslots" text, "customFieldsScheduledvisits" text, "customFieldsKycstatus" varchar(255), "customFieldsPannumber" varchar(255), "customFieldsOccupation" varchar(255), "customFieldsAlternatenumber" varchar(255), "customFieldsCibilscore" varchar(255), "customFieldsOrderid" varchar(255), "customFieldsAdvisorselleridid" integer, CONSTRAINT "REL_3f62b42ed23958b120c235f74d" UNIQUE ("userId"), CONSTRAINT "FK_90f47e7aa8cada41c7f407c0126" FOREIGN KEY ("customFieldsAdvisorselleridid") REFERENCES "seller" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3f62b42ed23958b120c235f74df" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "customer"("createdAt", "updatedAt", "deletedAt", "title", "firstName", "lastName", "phoneNumber", "emailAddress", "id", "userId", "customFieldsUserrole", "customFieldsAvailableslots", "customFieldsScheduledvisits", "customFieldsKycstatus", "customFieldsPannumber", "customFieldsOccupation", "customFieldsAlternatenumber", "customFieldsCibilscore", "customFieldsOrderid", "customFieldsAdvisorselleridid") SELECT "createdAt", "updatedAt", "deletedAt", "title", "firstName", "lastName", "phoneNumber", "emailAddress", "id", "userId", "customFieldsUserrole", "customFieldsAvailableslots", "customFieldsScheduledvisits", "customFieldsKycstatus", "customFieldsPannumber", "customFieldsOccupation", "customFieldsAlternatenumber", "customFieldsCibilscore", "customFieldsOrderid", "customFieldsAdvisorselleridid" FROM "temporary_customer"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_customer"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_73a78d7df09541ac5eba620d18"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_729b3eea7ce540930dbb706949"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_af13739f4962eab899bdff34be"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_124456e637cca7a415897dce65"`, undefined);
        await queryRunner.query(`ALTER TABLE "order" RENAME TO "temporary_order"`, undefined);
        await queryRunner.query(`CREATE TABLE "order" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "type" varchar NOT NULL DEFAULT ('Regular'), "code" varchar NOT NULL, "state" varchar NOT NULL, "active" boolean NOT NULL DEFAULT (1), "orderPlacedAt" datetime, "couponCodes" text NOT NULL, "shippingAddress" text NOT NULL, "billingAddress" text NOT NULL, "currencyCode" varchar NOT NULL, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "aggregateOrderId" integer, "customerId" integer, "taxZoneId" integer, "subTotal" integer NOT NULL, "subTotalWithTax" integer NOT NULL, "shipping" integer NOT NULL DEFAULT (0), "shippingWithTax" integer NOT NULL DEFAULT (0), "customFieldsSchedulevisit" datetime(6), "customFieldsSalespersonname" varchar(255), "customFieldsSalespersoncontact" varchar(255), "customFieldsSalespersonemail" varchar(255), "customFieldsAdvisorselleridid" integer, "customFieldsVisitstatus" varchar(255), "customFieldsScheduledvisitdate" datetime(6), "customFieldsAdvisornotes" varchar(255), "customFieldsLoantype" varchar(255), CONSTRAINT "FK_2efb279cc9029a1fb00b99d961b" FOREIGN KEY ("customFieldsAdvisorselleridid") REFERENCES "seller" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_124456e637cca7a415897dce659" FOREIGN KEY ("customerId") REFERENCES "customer" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_73a78d7df09541ac5eba620d181" FOREIGN KEY ("aggregateOrderId") REFERENCES "order" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "order"("createdAt", "updatedAt", "type", "code", "state", "active", "orderPlacedAt", "couponCodes", "shippingAddress", "billingAddress", "currencyCode", "id", "aggregateOrderId", "customerId", "taxZoneId", "subTotal", "subTotalWithTax", "shipping", "shippingWithTax", "customFieldsSchedulevisit", "customFieldsSalespersonname", "customFieldsSalespersoncontact", "customFieldsSalespersonemail", "customFieldsAdvisorselleridid", "customFieldsVisitstatus", "customFieldsScheduledvisitdate", "customFieldsAdvisornotes", "customFieldsLoantype") SELECT "createdAt", "updatedAt", "type", "code", "state", "active", "orderPlacedAt", "couponCodes", "shippingAddress", "billingAddress", "currencyCode", "id", "aggregateOrderId", "customerId", "taxZoneId", "subTotal", "subTotalWithTax", "shipping", "shippingWithTax", "customFieldsSchedulevisit", "customFieldsSalespersonname", "customFieldsSalespersoncontact", "customFieldsSalespersonemail", "customFieldsAdvisorselleridid", "customFieldsVisitstatus", "customFieldsScheduledvisitdate", "customFieldsAdvisornotes", "customFieldsLoantype" FROM "temporary_order"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_order"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_73a78d7df09541ac5eba620d18" ON "order" ("aggregateOrderId") `, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_729b3eea7ce540930dbb706949" ON "order" ("code") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_af13739f4962eab899bdff34be" ON "order" ("orderPlacedAt") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_124456e637cca7a415897dce65" ON "order" ("customerId") `, undefined);
   }

}
